DevOps study group plan - Initial Draft
devupin/activities pull request #2
Opened 2021-08-05 17:01 UTC by ninadsp

Draft based on current conversations between volunteers and expectations from participants in the first call!

2021-08-08 09:22 UTC, SathyaBhat approved these changes

2021-08-08 11:10 UTC, avinassh requested changes

2021-08-08 11:10 UTC, avinassh commented on devops.md
> +- so on...
could you add more to this schedule? dates for 2-3 sessions?

2021-08-27 07:18 UTC, ninadsp commented on devops.md
> +- so on...
Updated the TL, please review? Should we include a gap in the middle for Ganpati dates, or any other national holidays that we should be considering?

2021-08-27 07:51 UTC, avinassh commented on devops.md
> +- so on...
yeah, adding gaps and holidays help, lets people plan better. 

the PR looks good and can be merged. I approving it now. let me know if you want to add gaps etc or else I will merge

2021-08-27 07:51 UTC, avinassh approved these changes

2021-08-28 03:11 UTC, merged